import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generatePDFReport = (result, filename) => {

    const doc = new jsPDF();

    // Header
    doc.setFontSize(22);
    doc.setTextColor(30, 64, 175);
    doc.text("Deepfake Voice Analysis Report", 20, 20);

    doc.setFontSize(11);
    doc.setTextColor(100);

    doc.text(
        `Generated: ${new Date().toLocaleString()}`,
        20,
        30
    );

    // Table
    autoTable(doc, {

        startY: 45,

        head: [["Field", "Value"]],

        body: [

            ["Filename", filename],

            ["Prediction", result.prediction],

            ["Confidence", `${result.probability}%`],

            ["Confidence Level", result.confidence],

            ["Model", result.model_name],

            ["Processing Time", `${result.processing_time_ms} ms`],

        ],

    });

    // Footer
    doc.setFontSize(10);

    doc.setTextColor(150);

    doc.text(

        "Generated by Deepfake Voice Authenticator",

        20,

        270

    );

    doc.save("Deepfake_Analysis_Report.pdf");

};